### ISSUE TITLE
Register registry

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#108]
We need a registry to advertise some singletons.

**Comment by neithernut** [comment]
Blocks #107.

**Comment by matthiasbeyer** [comment]
What do you mean _exactly_ with "registry"?

**Comment by neithernut** [comment]
See `wayland_server.h` or the documentation.

**Comment by matthiasbeyer** [comment]
Okay. I understand the very idea of a registry. But a few questions are popping up:
- Who is the "server" in the context of [the documentation](http://wayland.freedesktop.org/docs/html/protocol-spec-interface-wl_registry.html)? The compositor? So do we have to emit events and stuff always when a new monitor gets plugged in? Really? I really cannot belive that we have to care about such low-level stuff!
- How do others implement the registry related stuff? Maybe it would be worth a look into the KDE codebase (or the swc thingy) or something, for this stuff?

**Comment by neithernut** [comment]
Well, if you want to look at the KDE codebase, enjoy the AIDS.
Also, it's not that lowlevel.
Considering the wayland library already ships a complete solution for a shared memory, it may also ship the registry itself. In this case, it still has to be initializes, though.

**Comment by neithernut** [comment]
The wayland library already handles registry. It implements the `get_registry` method for `wl_display`, including creation of the registry.
