### ISSUE TITLE
Prepare build env

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#11]
Dependencies:
- libreset
- wayland
- libinput
- check (for testing)
- JSON library decided in #10

Anything else?

**Comment by neithernut** [comment]
icu (unicode)

**Comment by neithernut** [comment]
I suspect that I should be the assignee here.

**Comment by TheNeikos** [comment]
@neithernut That shouldn't really matter I think. Things that are getting done get done. Whose name displays next to an issue doesn't seem important to me.

**Comment by neithernut** [comment]
That's true, but it _can_ cause confusion.

**Comment by neithernut** [comment]
Blocks #23.
