### ISSUE TITLE
Blit buffers onto monitors

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#115]
After the initialisation of the framebuffer, we need some code which iterates over all the buffers and blits them onto the framebuffer.

**Comment by neithernut** [comment]
Best would be some method to blit buffers.

**Comment by TheNeikos** [comment]
This can be closed

**Comment by neithernut** [comment]
The actual blit of surfaces is still missing. This will be integrated with #148.

**Comment by TheNeikos** [comment]
Hm, you are right.

**Comment by neithernut** [comment]
Will not be integrated with #148, but some time after the compositor interface is implemented.

**Comment by neithernut** [comment]
After the referencing issues are closed, we may close this one, finally reaching the milestone.
This is, after testing whether it works, of course.
