### ISSUE TITLE
Add capabilities for deadlock-free locking

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#117]
We need functions which enable us to savely lock multiple values.

**Comment by matthiasbeyer** [comment]
Is there some mechanism around to approach this, or do we have to implement this ourselves?

**Comment by matthiasbeyer** [comment]
I guess this is a "static method" for the `ws_object` type, right?

**Comment by neithernut** [comment]
I started a PR already. I think you have to leave this one to me.

**Comment by matthiasbeyer** [comment]
But this (#119) is not a PR for locking _multiple_ values!

I would assume something like `ws_object_lock_objs_read(o1, o2, o3);` or something coming out of this issue, not a `trylock()` functionality!

**Comment by neithernut** [comment]
You can lock a various number of values using nothing but a `try_lock` and be perfectly save concerning deadlocks.

**Comment by matthiasbeyer** [comment]
But it generates _some_ overhead in the code which could be prevented. For example:

``` c

if (!_trylock(a)) {
    goto err;
}

if (!_trylock(b)) {
    goto err;
}

if (!_trylock(c)) {
    goto err;
}
// ...
```

vs.

``` c
if (!_trylock(a, b, c)) {
    goto err;
}
```

You know what I mean?

**Comment by neithernut** [comment]
You may still have a locking function using va_lists, but that may be ugly.
You also have to put everything in a loop, so you retry to lock all the objects.

---

I will push code tomorrow, probably on #119.

**Comment by neithernut** [comment]
As #119 is merged, I'll probably do this at some point in another PR.
