### ISSUE TITLE
strdup for real libcs

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#124]
We will need some `strdup` implementation for non-gnu-libcs.
Since the wayland code is busted with linux-specifics, this has a low priority.

**Comment by neithernut** [comment]
This should go into `util/compat.h` and `util/compat.c`

**Comment by neithernut** [comment]
Relates to #128.

**Comment by matthiasbeyer** [comment]
`strdup()` is in POSIX1-2001, says my manpage:

``` plain
CONFORMING TO
       strdup() conforms to SVr4, 4.3BSD, POSIX.1-2001.
```

And `strndup()`:

``` plain
CONFORMING TO
       strndup() conforms to POSIX.1-2008.  
```

So this can be closed.
