### ISSUE TITLE
Make the CI do a merge before building?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#127]
I guess it would be beneficial to do a merge (on the CI server) with the development branch before building the software.

I don't know what kind of effect that would have when starting release-branches or hotfix branches on a release.

Please discuss.

**Comment by TheNeikos** [comment]
Why would you do that? If you have not rebased yet it might fail and you will wonder why. (Your codebase won't be the same in the testing env)

**Comment by matthiasbeyer** [comment]
It ensures us that we get a working version _after_ the merge, which is much more important than a working version _on_ the branch.

**Comment by neithernut** [comment]
I agree with that.

**Comment by matthiasbeyer** [comment]
@neithernut me or @TheNeikos ?

**Comment by neithernut** [comment]
How about the last post before mine?
It's you statement.

**Comment by matthiasbeyer** [comment]
Yes, but you were so fast that I assumed you posted at the very same moment and meant @TheNeikos comment.

**Comment by TheNeikos** [comment]
That doesn't matter though, github already tells you if you can merge or not. So it's not like a working build will suddenly make you be able to merge.

**Comment by neithernut** [comment]
There are, however, situations, where the merge results in non-building software.
E.g. consider a branch which uses a function which was removed in the development branch. The branch is mergable, but the result will be a linker error (undefined reference).

**Comment by matthiasbeyer** [comment]
Exactly. 

It doesn't matter if your branch merges or not, that is covered by github, as you already said. But if it is able to get merged, it could still break the build. If your PR isn't mergeable, you have to fixup anyways!

We had such situations already, where the `ws_object_unlock_read()` functions were made deprecated. This breaks the build for the development branch, if (and only if) you merge things which are based on a version where the function was not deprecated.

**Comment by TheNeikos** [comment]
Alright, that sounds reasonable.

**Comment by matthiasbeyer** [comment]
I'd like to read the opinions of @xVin and @manuelmessner on this!

**Comment by xVin** [comment]
Doing the merge before building sounds like a good idea to me. We should try it.
