### ISSUE TITLE
We need some O_CLOEXED replacement for non-linux

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#128]
We need something like

``` C
#ifndef O_CLOEXED
#define O_CLOEXEC 0
#endif
```

in `util/compat.h`

**Comment by neithernut** [comment]
Relates to #124.

**Comment by TheNeikos** [comment]
This is not yet necessary as our _complete_ graphical backend is currently based on the Linux Kernel subcomponent called _DRM_ aka **DirectRenderingManager**. It wouldn't make sense to implement just this for a case that we do not support. (Yet)

**Comment by neithernut** [comment]
Is marked as "on hold" now.

**Comment by matthiasbeyer** [comment]
I'd like to suggest to add the "reopen later" label and close this one.

**Comment by neithernut** [comment]
This would also apply to #124.

**Comment by neithernut** [comment]
There is some replacement for this in the drm header. We should use this one, since the only place we use this flag is in the drm backend.
