### ISSUE TITLE
Add initial basic module interface of the compositor

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#14]
The compositor needs some data for basic operation. For now, these may include:
- OpenGL context
- Some sort of monitor handles (integrated in Objects)

A stub for the initialisation function needs to be added, too.

**Comment by neithernut** [comment]
Blocks #15.

**Comment by matthiasbeyer** [comment]
You mean, we should have an class `ws_monitor`? You should add this to #30 then!
