### ISSUE TITLE
`make test` or `ctest` results in "No tests were found"

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#149]
The test setup seems to be buggy in some way.

I would also like to open a discussion about what could already be tested and how, also multithreaded tests and so on. We should start adding tests at least for the basic stuff.

This discussion could go into this issue and I would like to hear opinions from all of you!

**Comment by neithernut** [comment]
Mh... the setup works for me...

**Comment by matthiasbeyer** [comment]
Okay... this time it also worked for me. Maybe I didn't `cmake .` after the tests were added, I'M sorry.

**Anyway** I would like to add tests. But I guess this should be in another issue. Feel free to close.
