### ISSUE TITLE
Implement a serializer for JSON

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#151]
We need a serializer for the JSON format, which deserializes messages as described in the specification.
This will probably need some clarification. Please give me a call if you need some infos or hints.

**Comment by matthiasbeyer** [comment]
Do we need to define the structure of the internal transaction/command representation for this?

**Comment by neithernut** [comment]
Yep, when you implement the message type which holds transactions.

**Comment by matthiasbeyer** [comment]
Where should these types be located in the source? `src/objects` ?

I would add these types:
- ws_transaction
- ws_command
- ws_command_argument

and maybe more. SYN?

**Comment by neithernut** [comment]
Nope. Either in the command-processor's directoy or a directory on it's own.

---

The type names are OK, but you forgot about `ws_message`.

**Comment by matthiasbeyer** [comment]
Okay, so I'll put it into `src/command`.

The suggested types are okay?

**Comment by neithernut** [comment]
Yep.

**Comment by matthiasbeyer** [comment]
@neithernut Can you explain to me how to implement a JSON backend on your setup? (As soon as it is merged)

**Comment by neithernut** [comment]
Blocks #236.
