### ISSUE TITLE
Implement the ws_connector

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#160]
The `ws_connector`, which is btw _not an object_, has to be implemented according to spec.
Additionally to the stuff the spec says, a read-only mode should be added, which simply does not initialize or use the `outbuf`.

The initialisation funtion should take an file descriptor along with the connector itself.

**Comment by xVin** [comment]
Do you think I could try doing this? 
I'd like to give it a shot. :-)

**Comment by matthiasbeyer** [comment]
@xVin : I think you can do the interface, which should be one PR. But not the implementation, this is far to heavy IMHO for you by now.

**Comment by xVin** [comment]
kk, I'll do the interface then. 
As for the implementation: Maybe we could do it pair programming style? 
But if you think it's too far above my head, that's ok...

**Comment by xVin** [comment]
Seeing that this was assigned to manu: Am I still 'allowed' to do the interface?

**Comment by neithernut** [comment]
Yes, of course.

**Comment by matthiasbeyer** [comment]
@xVin How much is done?

**Comment by xVin** [comment]
Expect the PR this evening.

**Comment by neithernut** [comment]
Blocks #219.

**Comment by xVin** [comment]
Can be closed.
