### ISSUE TITLE
Make `struct ws_wayland_buffer` a `struct ws_buffer`?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#170]
In the source code of `struct ws_wayland_buffer` is written that it has a member called `buf` but is this necessary?

Couldn't simply `ws_wayland_buffer` be a subtype of `ws_buffer`?

@TheNeikos asks this as well.

**Comment by neithernut** [comment]
Could be done.

**Comment by neithernut** [comment]
Ah crap, I didn't think har enough. This doesn't work!
`ws_wayland_buffer` is a `ws_wayland_obj`, so it can't be a `ws_buffer`.

**Comment by neithernut** [comment]
One could swap the `ws_buffer` with the `ws_wayland_obj`, of course...

**Comment by matthiasbeyer** [comment]
I would like you to add a _very_ verbose documentation in the related file, what you're doing there.

**Comment by neithernut** [comment]
Could you be more precise?

**Comment by matthiasbeyer** [comment]
The multi-inheritance thing you're doing, it should be explained why and how.

**Comment by neithernut** [comment]
I'll add more documentation as soon as I can spare the time...

**Comment by matthiasbeyer** [comment]
I assume this can be closed? Don't know...

**Comment by neithernut** [comment]
Well...

**Comment by matthiasbeyer** [comment]
Well?

**Comment by neithernut** [comment]
Leave this open until I decided what to do, which implies having time to work on this issue.

**Comment by neithernut** [comment]
As shown by the newest addition, the decision of having the wayland buffer _contain_ a `ws_buffer`  was right.
