### ISSUE TITLE
Add a cursor

### ISSUE THREAD

**Issue by TheNeikos** [waysome/waysome#179]
For now it would be sufficient if the mouse would be just placed at the top left or some other position.

**Comment by TheNeikos** [comment]
It should read an image on the file system and should be placed _over_ every other type of buffer.

This is where compositing comes into play

**Comment by neithernut** [comment]
Yep. Wasn't there a way to pass a plane to libdrm and marking it as a pointer/arrow? I thought I saw something there...

Note: virtually all modern graphics cards support hardware based pointer drawing, and most people use this.

**Comment by TheNeikos** [comment]
Yup! That's what we are going to use
