### ISSUE TITLE
Add testing: ws_array type

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#180]
Testing for the array type should be added.

**Comment by matthiasbeyer** [comment]
@neithernut , @TheNeikos Do we actually need the array type? I wouldn't put effort into this if the array types gets removed anyway!

**Comment by neithernut** [comment]
Mh... I will check this when I'm back in FuWa.

**Comment by neithernut** [comment]
The array type can be dumped.

**Comment by matthiasbeyer** [comment]
I will throw this (ws_array) out now.

**Comment by neithernut** [comment]
The type was removed. Testing is thus not an issue we have to resolve.
