### ISSUE TITLE
Take the framebuffer creation out of the monitor

### ISSUE THREAD

**Issue by TheNeikos** [waysome/waysome#185]
We need to be able to create a framebuffer on a given monitor, but not actually set it as it's 'default' framebuffer.

This is for things like Double Buffering and the Cursor.

**Comment by TheNeikos** [comment]
Blocks #179

**Comment by neithernut** [comment]
The original idea was to have the `ws_buffer` interface abstracting such things. You would have some background buffer(s) and switch them on `ws_buffer_end_access`, for example, to implement double buffering. This way you'd have transparent buffer handling using one unified interface.

**Comment by TheNeikos** [comment]
That works for me. How would you implement such a thing with ws_buffer? A special `ws_frame_buffer_create` method that returns a `ws_frame_buffer` and thus implicitely a `ws_buffer`?

**Comment by neithernut** [comment]
Yep, you create a new derivate of `ws_buffer` and a constructor (like `ws_frame_buffer_new`) returning such an object.

**Comment by neithernut** [comment]
If you feel the need, you can, of course, extend the `ws_buffer` type. (e.g. for an explicit flip)
