### ISSUE TITLE
Add initial object implementation

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#19]
Implement the "object" struct according to spec.
The methods can be stubs.

**Comment by neithernut** [comment]
Blocks #16.

**Comment by matthiasbeyer** [comment]
I'd like to do this. Am I allowed to open issues for class implementation for:
- array
- stack
- queue
- string

and maybe others (which all will be blocked by this one, then)? I would assign them to others, then.

**Comment by xVin** [comment]
Feel free to assign something from that list to me as well (maybe sth rather simple for starters would be best, though). :)

**Comment by neithernut** [comment]
Note: this issue concerns only `ws_object` itself.
@matthiasbeyer I'll open those issues as needed or if there are resources free for this.

**Comment by matthiasbeyer** [comment]
@xVin I will do that.

**Comment by matthiasbeyer** [comment]
@neithernut Ok. Thanks

**Comment by neithernut** [comment]
The corresponding PR was merged.
