### ISSUE TITLE
Find a default cursor

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#197]
We should ship a default cursor, in PNG format.
We either have to make our own or find one. There are websites which give you tons of free icons. You have to look out for compatible licensing, however.

**Comment by xVin** [comment]
Would you prefer a white or a black default cursor?

**Comment by matthiasbeyer** [comment]
I'm trying to do this right now, but I guess competing approaches would be nice, so go for it.

I'd like to suggest to ship both, a white-black and a black-white one!

**Comment by neithernut** [comment]
You could easily invert the cursor, so it doesn't really matter if it's black or white.

**Comment by matthiasbeyer** [comment]
![BLACK OR WHITE; YEAR](http://itunes-music.com/wp-content/uploads/2012/07/michael-performing-black-or-white.jpg?eb8c7d)

**Comment by matthiasbeyer** [comment]
[My approach](http://webuser.hs-furtwangen.de/~beyermat/cursor.png)

**Comment by neithernut** [comment]
I created a smaller variant from your version. Additionally, I added a version with a small effect:
http://webuser.hs-furtwangen.de/~ganzjuli/waysome/cursor/

**Comment by matthiasbeyer** [comment]
Looks good, too. But I don't see the difference besides in size. And I don't see the effect.

**Comment by xVin** [comment]
He means the shading effect.

**Comment by neithernut** [comment]
The shading effect is meant to be minimal. This gives the cursor a little bit of depth without distracting the user.
