### ISSUE TITLE
Add type ws_string

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#20]
The type `ws_string` has to be implemented.
For now, most operations can be stubs. Initialisation and descrution however, must be implemented in a PR targeting this issue.

**Comment by neithernut** [comment]
@xVin: if you're ok with this, I'll assign this issue to you as soon as you accepted the invitation sent to your email (regarding membership of "waysome")

**Comment by xVin** [comment]
Oh, I overlooked the mail. I just joined. Go ahead and assign it :)

**Comment by matthiasbeyer** [comment]
Blocked by #19

**Comment by matthiasbeyer** [comment]
As the string implementation should consider Unicode, which requires interaction with a library, I wouldn't assign this one to @xVin , @neithernut . If @xVin is fine with it, okay... but there should be simpler tasks!

**Comment by neithernut** [comment]
If we do not implement the _complicated_ methods, the string type should be easy to implement (we don't need icu for allocation and deallocation).

**Comment by matthiasbeyer** [comment]
Of course, but I guess for string operations, they are neccessary! And we _will_ have string operations.

**Comment by neithernut** [comment]
Yep, but that will be the targeted in other issues.

**Comment by matthiasbeyer** [comment]
Ok.

**Comment by matthiasbeyer** [comment]
@xVin Go.

**Comment by neithernut** [comment]
Blocks #64.

**Comment by neithernut** [comment]
Blocks #30.

**Comment by matthiasbeyer** [comment]
Blocks #35
