### ISSUE TITLE
Reorganize Compositor

### ISSUE THREAD

**Issue by TheNeikos** [waysome/waysome#215]
Right now the compositor looks like this:

```
compositor/
├── background_surface.c
├── background_surface.h
├── buffer.c
├── buffer.h
├── frame_buffer.c
├── framebuffer_device.c
├── framebuffer_device.h
├── frame_buffer.h
├── internal_context.h
├── module.c
├── module.h
├── monitor.c
├── monitor.h
├── monitor_mode.c
├── monitor_mode.h
├── surface.c
├── surface.h
├── wayland_buffer.c
├── wayland_buffer.h
├── wayland_compositor.c
├── wayland_compositor.h
├── wayland_pointer.c
├── wayland_pointer.h
├── wayland_shell.c
├── wayland_shell.h
├── wayland_shell_surface.c
└── wayland_shell_surface.h
```

Which is not ideal.

`background_surface.h` actually defines `ws_image_buffer` we have `surface.h` defining `ws_surface` (Which is a wayland type!)

It think it would be best to introduce two sub folders called `buffer` and `wayland` in which we can then put the appropriate files. Thoughts?

**Comment by matthiasbeyer** [comment]
Sounds good. We could even short-cut "wayland" to "wl", I guess. Maybe that's an idea, maybe you guys don't like it.

**Comment by TheNeikos** [comment]
Doing this now.
