### ISSUE TITLE
Add code for reading the config file

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#220]
We need to locate the configuration file, open it and trigger processing it.

**Comment by matthiasbeyer** [comment]
Notes:

The configuration file _can_ be in various places:
- /etc/waysome.conf
- ~/.config/waysome.conf
- ~/.waysome/waysome.conf
- ~/.waysome.conf

More?

**Comment by neithernut** [comment]
Spamming the home directory? That's a bad practice.

---

I'd propose checking the following locations (in that order):
- `waysome.conf` (in the local directory, as in `$PWD`)
- `~/.config/waysome.conf`
- `~/.config/waysome/waysome.conf`
- `/etc/waysome.conf`
- `/etc/waysome/waysome.conf`

**Comment by matthiasbeyer** [comment]
What about `~/.waysome.conf` ? Or whats about `XDG_HOME`?

**Comment by neithernut** [comment]
On desktop machines, there are more than enough hidden files sitting around in the home directory. Modern applications often use the `~/.config/` directory and so should we.
We _could_ look into the XDG config directory and `$XDG_HOME`, however.

**Comment by matthiasbeyer** [comment]
sounds reasonable to me.

**Comment by matthiasbeyer** [comment]
Another Idea I just had: Why not depending on one env-variable and maybe the `etc/waysome.conf` ? That would be much less overhead. Or are there any major disadvantages with this?

**Comment by neithernut** [comment]
Yep: you have to set your environment. Sane defaults are _always_ preferable.

**Comment by neithernut** [comment]
Relevant bits regarding env-cars: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
