### ISSUE TITLE
Unify include path in compositor

### ISSUE THREAD

**Issue by TheNeikos** [waysome/waysome#223]
right now there are absolute and relative includes _all over the places_

**Comment by TheNeikos** [comment]
Will do that next

**Comment by matthiasbeyer** [comment]
:+1:

**Comment by neithernut** [comment]
Absolute paths.

**Comment by matthiasbeyer** [comment]
@neithernut Why did you close this, it's not yet done!

**Comment by neithernut** [comment]
It's solved in the branch for compositor reorganisation...
