### ISSUE TITLE
Add image loading libraries to build environment

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#23]
We need to add some libraries for image loading (e.g. [libpng](http://www.libpng.org) and libsvg) to the build env (as dependencies).

**Comment by neithernut** [comment]
Blocks #22.

**Comment by matthiasbeyer** [comment]
Why?

**Comment by TheNeikos** [comment]
Because of #22

**Comment by matthiasbeyer** [comment]
I think "Because of the background image" would be a much better answer. But yes.

**Comment by neithernut** [comment]
libpng is in the build environment. I think this is sufficient _for now_.

**Comment by neithernut** [comment]
Libsvg is not included yet, but libpng is sufficient for now. We will open additional issues as soon as someone asks for support for more formats.
