### ISSUE TITLE
Add CMake module for finding libinput or libevdev

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#232]
A CMake Module has to be written which searches for libinput. The existing Modules may be used as a template for this.

**Comment by neithernut** [comment]
I was just looking into `libinput` more closely and I realized that it was actually using [libevdev](http://www.freedesktop.org/wiki/Software/libevdev/) under the hood.
The things libevent actually does, seem to be:
- automatically identifying new devices, which is a very minor thing
- grouping devices into seats it supports, which is a very minor thing, too
- abstracting events by as good as nothing
- dispatching events (ah god, not again! More epoll bullshit!)

Considering all the quirks `libinput` has in it's code (like shipping copies of internal linux headers etc.), I think we really want to use `libevdev` directly. Finding new devices is elementary, recieving events is dead simple. The amount of code to be written should be not so different with both libraries.

**Comment by matthiasbeyer** [comment]
> Considering all the quirks libinput has in it's code (like shipping copies of internal linux headers etc.)

Whenever I read somethink like this, I consider saying "Hey, why don't you write to the developers of that library and request a fix for this", so I'll do this now:

Hey, why don't you write to the developers of that library and request a fix for this?

**Comment by neithernut** [comment]
Because the only way to do this would be a complete rewrite.
And I don't care enough about people using shitty libraries if they don't need to.
And this fact is actually known to them. They just don't care enough to change it (ATM).
