### ISSUE TITLE
[Request] `ws_command` interface enhancements

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#233]
For my work on the JSON deserializer, I need some more functionality in the `ws_command` type interface:
- Construct a command object, plain, without any values set
- Setters/Getters for 
  - Command name
  - Command type
- Arguments modification
- A finalizer method for "Hey, here is a command, fill out all values I didn't" or something like that

Also, the getter by name should be chaned to return a new `ws_command` object, so I can modify it. 

I need this ASAP.

**Comment by neithernut** [comment]
I think you don't quite understand how these things work...
Look at the documentation. All these fields are public _for a reason_.
Also: you don't have a sequence of commands, but of `ws_stantement`s.
And "Fill out all values I didn't" is plain bullshit.

**Comment by neithernut** [comment]
Concering arguments: have a `ws_array`, collect all the arguments and then memcpy them into the statement.
Same goes for the statements.

**Comment by matthiasbeyer** [comment]
What is that `ws_statement` you're talking of? I don't know that type.

**Comment by neithernut** [comment]
Look at `src/command/command.h`

**Comment by neithernut** [comment]
I'll assume this can be closed now...

**Comment by matthiasbeyer** [comment]
ACK.
