### ISSUE TITLE
Add the command processor

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#236]
The command processor needs to be implemented. This is quite an easy task as it will just fetch data from the connectors, use the deserializer to get messages, feed them to the action manager and push messages to the client unsing the connector and the serializer, it the connection in not read only.

**Comment by neithernut** [comment]
Blocks #219.

**Comment by xVin** [comment]
If this has time until tomorrow, I'd like to do it. (Gotta prepare a presentation first this evening.)

**Comment by matthiasbeyer** [comment]
Isn't this what #235 covers? Or am I messing up two different things here?

**Comment by neithernut** [comment]
Nope, this is another thing.
While the _action manager's processor_ processes single transactions, the _command processor_ is the component which reads from the connector, deserializes a message and then eventually pushes that message to the action manager, serializes the result and pushes it back over the connector.

**Comment by neithernut** [comment]
I'm currently on this, to save some time (nothing else to do right now...).
