### ISSUE TITLE
Add return message type

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#241]
We need a message type for return messages.

**Comment by neithernut** [comment]
Blocks #240.

**Comment by matthiasbeyer** [comment]
For the naming: This should be named "answer" or "response" (which is stated in the spec with this name, I guess).

**Comment by neithernut** [comment]
I'll look it up. I'm on it btw.

**Comment by matthiasbeyer** [comment]
:+1:

**Comment by matthiasbeyer** [comment]
Let me add a short note/question: A result message should be a bit of an abstract type, as a result can either be an answer or an error. I don't know yet how to do the abstraction here, but we clearly need to have some kind of "supertype" for this.
