### ISSUE TITLE
Transactions don't have their own object type id

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#244]
The entire object type id stuff is missing from `ws_transaction`.

**Comment by matthiasbeyer** [comment]
For clearification: Not the object supertype is missing but the id stuff! (just if someone else then you implements this).

**Comment by matthiasbeyer** [comment]
@neithernut Tell me what to do exactly (callbacks, I assume?) and assign me (Or review my PRs so I can continue).

**Comment by neithernut** [comment]
Add the static struct needed for a type. Except for the init callback, all the callback fields may be set to `NULL`.

**Comment by matthiasbeyer** [comment]
The init callback is unused, so this is `NULL` either!
