### ISSUE TITLE
Add connection accept()ing code

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#259]
We need to create a socket plugins can connect to. We also have to `accept()` connections from it.

**Comment by matthiasbeyer** [comment]
Is there anything done yet?

**Comment by manuelmessner** [comment]
> Is there anything done yet?

Yes there was nearly everything done when my hard disk crashed.
My system is reinstalled and configured right now. So i'll rewrite it.
It should be finished soon.

**Comment by matthiasbeyer** [comment]
I hope you get the point of `git push` now.

**Comment by manuelmessner** [comment]
yeah -.-

**Comment by matthiasbeyer** [comment]
:angry:

**Comment by matthiasbeyer** [comment]
@manuelmessner There is still no PR around, are you actually doing something?

**Comment by manuelmessner** [comment]
You were sitting next to me when I was working on it today...

**Comment by neithernut** [comment]
Point is: when there's a PR, we can _assess_ the progress.

**Comment by manuelmessner** [comment]
I'll upload my PR when i have a working version or at least when it is nearly working, otherways the history will be a mess.

**Comment by neithernut** [comment]
You can still rebase a branch/squash commits after submitting a PR (as long as it isn't merged). The only thing you _can't_ do is rename the branch.

**Comment by matthiasbeyer** [comment]
@manuelmessner and me are currently on this.

@neithernut Please verify that the following is right:
- The accept()ing code creates the `ws_connection_manager\* instance for the connection
- ~~The accept()ing code creates _ws_connbuf_ instances for reading/writing~~

How does the code interact with the rest of the system, mainly speaking of de/serialization here? What to do with the `ws_connection_manager` after it got instantiated?

**Comment by neithernut** [comment]
The accepting code creates _processors_. Managers are __always singletons!_
