### ISSUE TITLE
Implement arithmetical commands

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#267]
The stubs are in `src/commands/arithmetical.c`. The first argument should be set to the result.

**Comment by xVin** [comment]
Please assign me if that's ok. I'm finally done with my presentation & ready to get back to work.

**Comment by matthiasbeyer** [comment]
@xVin The string is more critical atm.

**Comment by xVin** [comment]
String testing? Ya I thought I'd start doing this tomorrow & just wanted something small for today because I'm so tired.
If you refer to the string API commands, just assign me to that instead.

**Comment by xVin** [comment]
Ok, just read the other thread. I'll try to fix the string stuff first then.

**Comment by xVin** [comment]
As I can't work on the ws_string tests atm because of a problem with my build env (and the "unlock mystery"), I will do this first.
