### ISSUE TITLE
Add logical commands

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#268]
Bitwise operations may also be implemented.

**Comment by matthiasbeyer** [comment]
@neithernut Can you provide a list of steps what has to be done for this or how this is done? I would like to do this!

**Comment by neithernut** [comment]
Have a look at `src/command/CMakeLists.txt`. It contains a description on how to do things.

**Comment by matthiasbeyer** [comment]
I will implement the bitwise operations in a separate PR and open an issue for this right now (and self-assign it).
