### ISSUE TITLE
Class implementations

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#30]
This Issue tries to keep track of all classes we want to implement.
- ws_object (covered in #19, #27)
- ws_array (done by #51)
- ws_stack
- ws_string (covered in #20)
- ws_queue

Whereas the last one is the least important. I would like to open issues for each individual and assign them.

**Comment by matthiasbeyer** [comment]
@neithernut Am I allowed to open issues for the classes and assign them, as soon as #27 is merged?

**Comment by matthiasbeyer** [comment]
`ws_object` is done. `ws_array` and `ws_string` are in progress.

@neithernut reopen?

**Comment by matthiasbeyer** [comment]
`ws_wayland_obj` should also be added, as noted in #66 .

**Comment by matthiasbeyer** [comment]
The set type is covered in #86 .

**Comment by matthiasbeyer** [comment]
Are the stack type and a queue type required, @neithernut ? Shall we implement those?

**Comment by neithernut** [comment]
They are not required now and they will likely be not required later.

**Comment by matthiasbeyer** [comment]
I could imaging that we need a FIFO like structure for the mechanism which executes the transactions. But I guess we will open issues for these then. I will open a PR for removing the appropriate files.

Feel free to close this one at own will!

**Comment by neithernut** [comment]
As all the types now have their own issues to track them, we may indeed close this one.
