### ISSUE TITLE
Pass keyboard events to the application having focus

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#314]
For now, passign the keyboard input directly to the application is sufficient.

**Comment by matthiasbeyer** [comment]
I would like to do this in pair-programming with @TheNeikos !

**Comment by TheNeikos** [comment]
![](http://www.peacethroughpie.org/wp-content/uploads/2013/09/baked-pie.jpg)

**Comment by neithernut** [comment]
![](http://qph.is.quoracdn.net/main-qimg-79db28e82ade28acb1cd7d054874b7ea?convert_to_webp=true)
