### ISSUE TITLE
Add command for storing a value

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#331]
This would be a special command, which would read the `top` (or some argument passed directly) and put it into a position given to the command.
The decision which argument should come first is up to the one implementing this.

**Comment by matthiasbeyer** [comment]
You mean "put it into a position on the stack" by "put it into a position", right?

**Comment by neithernut** [comment]
Yeah....

**Comment by matthiasbeyer** [comment]
How should such a value be named. What parameters should it get?

Something like:

``` json
{ "set" : [ 1, {"pos": -4} ] }
```

for setting the 4th topmost value to 1? What do you have in mind for this?

**Comment by neithernut** [comment]
This would be sufficient.

**Comment by matthiasbeyer** [comment]
How should such a command be named? My suggestions:
- "putinstack" (not refering to Putin here...)
- "store"
- "stackstore"
- "stackpostoval"

maybe with underscores or dashes like so: "put-in-stack" etc.? I'm unsure about it...

**Comment by neithernut** [comment]
Why such long names? `store` or even `sto` are totally sufficient.

**Comment by xVin** [comment]
Though I have to admit "Putinstack" made me laugh :D
