### ISSUE TITLE
Drop info pages?

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#351]
The current setup is aimed at a info page and a man page, both generated from the same/similar sources. Now it turned out that the `latex2man` utility is not as usable as one may whish. And I, for my part, would not like to start writing `texinfo` documentation. (it's... ugly)

If we were to drop the info pages, there would be many options. E.g. we could generate the suer documentation in PDF and HTML format (using [TTH](http://hutchinson.belmont.ma.us/tth/), [tex2page](http://www.ccs.neu.edu/home/dorai/tex2page/index.html) or [another tool](http://ctan.org/topic/cvt-html)).
The man page could still be generated form a restricted subset of the sources for the manual (from a different main file) using `latex2man` or hand-crafted. Despite the problems we had with `latex2man`, I think the former is still a viable option (as `latex2man` is clearly meant to produce man pages).

**Comment by matthiasbeyer** [comment]
To get this discussion going: ACK. I would rather provide an extensive manpage then a crappy infopage and a short manpage.

Others do it this way, too, just look at the manpages of git. So I don't see any problem with a large manpage.
