### ISSUE TITLE
Implement Flag support for JSON deserializer

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#361]
The JSON deserializer is not yet capable of message flags. This should be implemented.

**Comment by matthiasbeyer** [comment]
@neithernut Please add a "prio" tag, I don't know how urgent this is.

**Comment by matthiasbeyer** [comment]
I guess we should discuss the format of the flags, as they are not simply booleans in some cases. I would suggest the following format:

``` json
"flags" = {
  "execute" : <boolean>,
  "register" : {
    "event-name" : <string>
  }
  ...
}
```

More fields?

**Comment by neithernut** [comment]
You actually don't register a transaction under an event name, but a transaction name. The mapping between events and transactions is done in a different place.
The registration should be a string, not an object.
Also, the execute flag should be `true` by default.

---

There are also a few other options I'd like to discuss on monday.

**Comment by matthiasbeyer** [comment]
Well, the `register` part was for attaching a transaction to an event, but well, it should be

``` json
"register": <transaction-name as string>
```

of course. Mapping a transaction to an event should be done in another way, of course.

The execution flag should be true, indeed. At this very moment, the serializer sets it automatically. This will change as soon as flags can be parsed, of course.
