### ISSUE TITLE
Add function table to object

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#365]
We need a way to issue methods trough the API. This should be implemented similarly as the attribute setting system using a table containing a method's name and a function pointer of a "regular command".

**Comment by neithernut** [comment]
Blocks #366.

**Comment by matthiasbeyer** [comment]
Q: Can you elaborate on the shape of this? The name thing is clear, but how should the function callbacks look like? They are 'regular command' functions, if I understand your description. But how do things work together, how is the actual object passed and so on?

Please provide naming examples for such a function callback. Is something like this sufficient:

``` c
ws_object_call(some_object, "to_string");
```

for example? What would happen behind the scenes besides the lookup of the `"to_string"` named method?

**Comment by neithernut** [comment]
A object id (pointing to the object on which to invoke the method) and the method name ("to_string" in this case) and the arguments should be on the stack.
The command should then lookup the method and invoke it, passing the stack as-is to the function callback.
