### ISSUE TITLE
Add commands for adding hotkey events to the context object

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#400]
There must be functions for adding hotkey events. While the backend versions of those functions exist already, they still have to be exported through the API.

**Comment by xVin** [comment]
I'd like to do this. Could start tomorrow.

**Comment by neithernut** [comment]
Sure, you have to wait for the backend to be merged, though.

**Comment by neithernut** [comment]
Deps are cleared now.

**Comment by matthiasbeyer** [comment]
> There must be functions for adding hotkey events. While the backend versions of those functions exist already, they still have to be exported through the API.

Which functions have to be exported?

Also: Can you elaborate on how the API calls must look like (meta-language is much enough here) and how they behave?

**Comment by neithernut** [comment]
- `ws_hotkey_add` taking a string, followed by ints as arguments
- `ws_hotkey_remove` taking ints as arguments
