### ISSUE TITLE
Add `ws_dbg` macro which expands only when compiling with debugging

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#401]
It should expand to a `ws_log()` if debugging is enabled.

**Comment by neithernut** [comment]
You want at least _some_ logs in release software.

**Comment by matthiasbeyer** [comment]
Of course, but not all of them. This macro is for doing `ws_log()` only if debugging is enabled, for example printing input events - you don't need to print every single event in the release software.
