### ISSUE TITLE
Make "current" surface(s) availible to transactions

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#420]
This is a purely conceptual issue which is not intended to have PRs attached to it directly. Other, more concrete issues, which will have PRs attached to them, will refer to this one.

This should generally be done by the contexts a transaction sees. In the end, this should be done by adding functions to retrieve the surfaces as `ws_value_object_id` from the contexts.
As it turns out, these are multiple surfaces:
- The surface having keyboard/mouse focus (via the global context)
- The surface being "unter the mouse" (via the event context)

Furthermore, the mouse enter- and leave-behaviour _might_ be redefined using events and transactions. E.g. moving the mouse over a window's border will not cause a direct emission of an event via wayland but cause an event to be emitted _or_ a transaction to be invoked directly.

**Comment by TheNeikos** [comment]
Blaze it

**Comment by matthiasbeyer** [comment]
@neithernut I'd like you to add some bullet points in the main comment of this issue, so we can track its progress more easily.

**Comment by neithernut** [comment]
You can track the progress using the reference indocators.

**Comment by neithernut** [comment]
All the issues referencing this one are closed now.
