### ISSUE TITLE
Make keyboard- and mouse-focus settable through the global context

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#421]
The title sais it all. However, don't be afraid to ask questions.

**Comment by matthiasbeyer** [comment]
I consider a interface to the mouse via the API as really critical (same concerns as @TheNeikos stated in #424).

**Comment by neithernut** [comment]
Note that this is _also_ neccessary to _change_ the focus _actively_ through hotkeys.

**Comment by matthiasbeyer** [comment]
But I guess this is only the keyboard focus. I'm not sure whether we want this for the mouse focus as well... @TheNeikos what do you think?

**Comment by TheNeikos** [comment]
See #424 for my answer
