### ISSUE TITLE
Not all `ws_object` type methods are thread safe

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#451]
Mainly speaking of `ws_object_instance_of()` here, but I guess others aren't, too. I will investigate.

**Comment by neithernut** [comment]
This special method doesn't need to be thread save as an arguments type doesn't change during runtime! This also holds true for a few other methods.

**Comment by matthiasbeyer** [comment]
I will investigate on the types anyways and improve where necessary.

**Comment by matthiasbeyer** [comment]
Just found: does the `ws_keyboard_send_keymap()` need locking on the passed `ws_keyboard` object? @TheNeikos ? 

---

Same for `..._send_enter()` and the like...

**Comment by matthiasbeyer** [comment]
Closed as the appropriate PR got merged.
