### ISSUE TITLE
ci.neikos.me appears to be down

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#454]

**Comment by matthiasbeyer** [comment]
http://www.downforeveryoneorjustme.com/ci.neikos.me

Down here, too. @TheNeikos is asleep, though. I try to investigate.

**Comment by matthiasbeyer** [comment]
Damn, it's not only the CI, it's the complete host. Fuck.

**Comment by matthiasbeyer** [comment]
Unfortunately, I can `ping` the host, but not enter via web interface somehow.

**Comment by neithernut** [comment]
I suggest _not_ performing any merges as long as the CI is down. We may, however, work on existing PRs and create new ones.

**Comment by matthiasbeyer** [comment]
Of course, I won't do any merges as long the CI is down!

**Comment by matthiasbeyer** [comment]
@TheNeikos is still asleep, at least we fail to contact him. Damn.
