### ISSUE TITLE
`src/connection/processor.{c,h}` is named inappropriately

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#458]
The files should be named `src/connection/manager.{c,h}` respectively, right?

The actual code inside uses the terminus "manager" instead of "processor", that's why I assume this to be wrong. Am I right?

**Comment by matthiasbeyer** [comment]
Should wait on #466 and maybe needs some discussion, as there is already a "manager" named file, ... but empty. @neithernut maybe you know what to do here?

**Comment by neithernut** [comment]
As expressed somewhere else, a _manager_ is a singleton whete a processor is an instance sitting on a connection, doing stuff.
