### ISSUE TITLE
Add `_new()` functions for ws_value_* types

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#477]
A `_new()` function for certain `ws_value` types would be rather simple, but simplify other code very much.

I guess we should go for it.

**Comment by neithernut** [comment]
The whole point of values is that we have _lightweight_ means of abstractions for types to put on the stack. Devs should be discouraged from putting them on the heap!

**Comment by matthiasbeyer** [comment]
But sometimes this is not possible, so functions to allocate & initialize them would be beneficial in some cases.

We could, though, add a comment to the interface here and state that stack allocated `ws_value*` objects should be preferred!

**Comment by neithernut** [comment]
We can _always_ use a value union instead!

**Comment by matthiasbeyer** [comment]
This is indeed an option.
