### ISSUE TITLE
Arithmetical commands do not support stack positions by now

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#491]
Maybe the bitwise and logical also do not support it.

Should be added and tests should be adapted.

**Comment by neithernut** [comment]
What do you mean by that? The stack is prepared by the action manager, not by the command itself!

**Comment by matthiasbeyer** [comment]
Yes, but the arithmetical, logical and bitwise commands do not support arguments via stack by now.

**Comment by neithernut** [comment]
Yes, they do.
