### ISSUE TITLE
Add `istype` command

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#492]
I think we need a command "isnil" to check whether an object on the stack is `NIL` or not.

I don't know whether this should go into an own file (`src/command/nil.*` for example), but I guess we need it, right?

**Comment by neithernut** [comment]
A way to check for the type of a value would be preferable.

**Comment by matthiasbeyer** [comment]
Hm. We have already "hastypename" for object related once, but I guess we need also one for the value types, yes. I will rewrite this issue for it.

**Comment by xVin** [comment]
May I do this?

**Comment by neithernut** [comment]
Yep.

**Comment by neithernut** [comment]
For clarification: the command should check the _value_'s type (got confused there myself).

**Comment by xVin** [comment]
Is it ok to put this into command/object.c or should it get its own file?

**Comment by neithernut** [comment]
I think a new file wouldl be preferable. Maybe `util` or something...

**Comment by matthiasbeyer** [comment]
I'm sorry I confused you guys...
