### ISSUE TITLE
Enable shutdown-hotkey by config

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#493]
I think we can now start putting soe functionality into the config. The most natural thing to start with is shutting down the compositor. This would be done by writing two transactions:
- A strored transaction which performs a shutdown
- A transaction which is executed right away which adds an appropriate hotkey

**Comment by matthiasbeyer** [comment]
Reminder for myself:

Next step for this issue would be the ability to trigger a transaction via hotkey. This should be done by registering the exit transaction for a hotkey and get it executed by pressing a key.
