### ISSUE TITLE
Change deserializer (on abstract/calling level)

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#510]
This is a question/proposal.

Long story short: I have some problems with the (json) deserializer. They can be solved, but they need some changes in the deserializer calling code and in the whole architecture of the deserializer (on a abstract level).

The "problem" I have is the streaming-parser library which sits behind the deserializer. It's fine to have it and I guess _even_ if there would be a port some time in far future, we still want to have a _streaming_ parser here.

The problem I've encountered is: The streaming parser does not support to "pause" the parsing in between, to process the generated output. We can stop it manually, but that causes it to fail when continuing (inside the lib, not in my backend). Anyways, all workarounds I thought about would result in uglyness.

My proposal:

Change the deserializer interface to a "queue" like behaviour: The parser backend parses the messages and puts them into a queue. That queue can be read from, returing parsed stuff.

That would result in really clean code in the json parser backend, as I just would need to push my already buffered message object into the queue and notifying others that there is something inside the queue. It would prevent us from an ugly "stop-process-continue-parsing" thing and result in a setup which would "translate" a binary stream into a message "stream", but without the need to stop processing of the binary data in between, which is much cleaner IMHO.

Suggestions would be welcome, notify me if the above explanation is not clear enough!

**Comment by neithernut** [comment]
Nope.
