### ISSUE TITLE
Rip out named value

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#511]
I just ran a grep over our code and saw that `value_union` is actually never used.
The type currently has some issues, which need to be fixed. However, we may as well rip it out of our code, **if** it's not needed by anyone.
Originally, it was meant for dictionaries. Question is whether we need this functionality as it was intended originally or not.
I think we can save us a lot of pain if we just remove this type.

**Comment by neithernut** [comment]
Would make #494 unnecessary.

**Comment by matthiasbeyer** [comment]
I agree with you.
