### ISSUE TITLE
Key combos are broken up too quickly

### ISSUE THREAD

**Issue by TheNeikos** [waysome/waysome#515]
We get the output 'All keys released' way too early.

To reproduce:

Press CTRL + ALT + Q, then release Q and you should see that message, might be related to #514

**Comment by neithernut** [comment]
I thnk this bug is a pure wording problem: the message is sent every time when a key is released if the keys pressed at that moment are not part of a key-combo.
I'll wrap my head around this one.

**Comment by TheNeikos** [comment]
Ah okay, that makes  sense
