### ISSUE TITLE
Pressing hotkeys really slow does not fire a transaction

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#534]
Might be related to #532 

Pressing "strg-alt-q" really slowly does not fire the registration which is mapped on these keys, whereas pressing them fast executes it.

Feel free to add appropriate prio.

**Comment by neithernut** [comment]
In the future, **do not file an issue whithout noting anything about potentially missing prequisites** or a working config to reproduce the bug, for that matter!
