### ISSUE TITLE
Check the transaction flags for the transaction which leave the deserializer

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#536]
Check whether the transaction flags for the transactions which get emitted by the deserializer are sane all the time.

**Comment by neithernut** [comment]
Transaction processing is fucke up. Fix it!
Blocks #534 and #532.

**Comment by matthiasbeyer** [comment]
This issue was actually opened because there is one flag to much for the config flie we're actually testing. The second transaction has only the exec-flag, but the register-flag is set for it as well... that's why I opened this issue...

**Comment by neithernut** [comment]
I only saw **one** transaction.
