### ISSUE TITLE
Set up developer's documentation

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#552]
At some point we agreed that we want a higher level developer's documentation. @matthiasbeyer and me more or less decided on using MD files in following setup:
- One MD file describing the overall architecture on module/package level, including
  - Short description of each module
  - Description of the interaction between modules
- Each module (`compositor`, `input` etc) should get _one_ MD-file, which:
  - describes the module in more detail
  - describes the interaction between classes
  - provides doxygen-links to the classes described
  - may link to (existing) pages describing some function in detail (e.g. `input/hotkeys.md`)
- `main.c` and `context.{h,c}` _may_ get a MD file on their own.

Obviously, the MD files will be embedded into the doxygen documentaiton, serving as introduction/module/group pages/sections.

This issue only covers creating the files with titles and labels. I'd suggest putting module specific documentation into another PR. If the asignee feels that way, he/she may, however, provide content.

**Comment by matthiasbeyer** [comment]
I fully aggree with you, besides one point: I don't think that the `main.c` needs an own documentation file.

But yes for everything else. The assignee should be careful with the location and how the files get embedded, some of the documentation files which do already exist are not put into the right documentation-group. A fix for this could possibly be covered by the assignee as well...
