### ISSUE TITLE
SIGILL when opening two weston terminals at the same time

### ISSUE THREAD

**Issue by TheNeikos** [waysome/waysome#568]
The problem is that `ws_object_unlock(x)` seems to unlock twice the same object which is obviously wrong and not what the code is doing.

Feel free to checkout my branch `add-compositing` to reproduce. 

`$ waysome` followed by 2x `$ weston-terminal` and you will get a SIGILL on the unlock.

**Comment by matthiasbeyer** [comment]
When I start `waysome` in `gdb` and then start `weston-terminal` in another terminal, the first one exits (no segfault). That's really strange!

Do I need to switch TTY?

**Comment by TheNeikos** [comment]
I have had trouble reproducing it now as well.

Perhaps it was a race condition? I rewrote stuff and it doesn't happen there anymore...

**Comment by matthiasbeyer** [comment]
okay.

**Comment by matthiasbeyer** [comment]
Anyways we should investigate a bit further... or, if you want, you can close this...

**Comment by matthiasbeyer** [comment]
Assigned low prio tag because this issue seems to be resolved already.

**Comment by neithernut** [comment]
I'll close this now. Reopen if this or a similar issue shows up again.
