### ISSUE TITLE
Double type?

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#584]
Do we actually need a double type?

I would implement one, if necessary (none of a big deal), but I doubt we need one. If not, this issue will track the progress on removing the code fragments for the double type introduction.

Relates #467

**Comment by neithernut** [comment]
I'd omit it for now. If we ever need doubles, or anyone asks for it, we can still implement it.

**Comment by matthiasbeyer** [comment]
I'll do this.

**Comment by matthiasbeyer** [comment]
Btw: This would also remove the object-attribute-reading/writing code for doubles, still ACK?

**Comment by neithernut** [comment]
Yep.
