### ISSUE TITLE
Implement set deserialization in the json deserializer

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#594]
The deserializer is not yet able to deserialize sets.

**Comment by neithernut** [comment]
Not possible ATM, as we have no relyable mepping from an id to an object.
Suggest tagging it as reopen-later and close it now.

**Comment by matthiasbeyer** [comment]
We still can implement the set support for it, for nils, ints and strings. The rest can be implemented on top of that really easily!

**Comment by neithernut** [comment]
K, but don't expect it to be of any use then.

**Comment by matthiasbeyer** [comment]
Why not? We need to deserialze sets, anyway! Deserializing of object id's inside sets is just an additional feature of the set deserialization, then... ?

**Comment by matthiasbeyer** [comment]
Fuck.

`ws_set`, which is underneath `ws_value_set` can only take `ws_object`s. I don't know whether this is what you mean, ... but I see that this isn't that easy without a huge amount of overhead...

**Comment by neithernut** [comment]
You're welcome.
