### ISSUE TITLE
Sanitize error handling in JSON serializer

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#635]
The JSON-serializer's error handling consists mostly of TODOs.
Relates to #467.

**Comment by matthiasbeyer** [comment]
@neithernut : Please comment on [this](https://github.com/waysome/waysome/blob/develop/src/serialize/json/serializer.c#L268) what to do? Do I need to free this buffer or does this someone else?

**Comment by neithernut** [comment]
You have to unref it once. (it's ref'd by a `ws_serializer` method)
