### ISSUE TITLE
Add callback for access of object internas

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#64]
We will need some way to implement an index operator for our transaction. This should be done by adding a callback to the object type.
It should take a `ws_string` and set/return a `ws_value`.
If that callback is `NULL`, the function should return `nil` automatically.

**Comment by matthiasbeyer** [comment]
An _index_ operator for the _object_ type?

**Comment by neithernut** [comment]
Yep. So you cann access internal values of an object, like the path of the background image for a monitor.

**Comment by matthiasbeyer** [comment]
Shouldn't such functionality be covered by the `set` type?

**Comment by neithernut** [comment]
Nope, that way wou would need to put a set in each and every object, just to access e.g. the width and the height of a window.
That would be completely and utterly unneccessary.

**Comment by matthiasbeyer** [comment]
Ah, ok. You mean something like a key-value storage, where you can access the values by key, right? And this is required for the API, right?

So... this is covered by the `ws_value_named` type, isn't it? We just need a way to put multiple of this (multiple key->value accociations) into one object.

**Comment by neithernut** [comment]
This would introduce imense overhead.

**Comment by neithernut** [comment]
@matthiasbeyer and I came up with a nice solution:

Each object type will have a sorted table with the following entries:
- Member name
- Member type
- Member offset in the real object
- Access modifiers (read/write)

The indexing method can then be implemented in the object type. Both the get and the set method will take a string and a value as a parameter. As the value denotes its type, the function can now search for a matching entry in the table and transfer/convert the internal datatype into the value apssed to the function.
Storing a value works similarly.
