### ISSUE TITLE
31c3 location

### ISSUE THREAD

**Issue by llohse** [waysome/waysome#658]
How do I find you guys? I don't see your assembly ;)

**Comment by neithernut** [comment]
It's the FuWaR assembly. It's beween the Lobby and the Hack-Center in the hall/room with the Spinny-Things hanging from the ceiling, the awesome tunnel and the info-desk. We're under one of those spinny-things _not_ spinnging, near ~~the Gehaimorganisation and BACKSPACE~~ Hackerspace Saarbrücken. There's a little improviced piece of paper hanging from the ceiling.
Ask for Matze, Jule or Neikos/Marcel.

**Comment by neithernut** [comment]
The congress is over now, so we're obviously not there any more.
