### ISSUE TITLE
Add unique ID to objects

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#66]
We forgot to add a unique ID to the objects.

**Comment by matthiasbeyer** [comment]
This could be done with 'libuuid' which is LGPLv2 and therefor fine.

**Comment by neithernut** [comment]
I'll add this to the build env.

**Comment by neithernut** [comment]
Blocks #65.

**Comment by neithernut** [comment]
"libuuid" is not an option, because the resulting uids are not densly packed.

**Comment by neithernut** [comment]
An incrementing counter should be sufficient. I'll submit a PR in a few hours.

**Comment by neithernut** [comment]
I thought I saw some functions for getting uids somewhere in the wayland spec. And I found them:
`wl_display_get_serial(struct wl_display* disp)` and `wl_display_get_next_serial(struct wl_display* disp)`
In the version 1.3 documentation, there is no annotation for these functions. But I suspect that you want to call `wl_display_next_serial()` to retrive new ids while the other function gives you the current id for logging/info purposes.

**Comment by neithernut** [comment]
It's acutally nonsensical to allocate a unique id for every string and every set we use, e.g. in an transaction.
We need those uids/serials only for a relatively small number of objects, which will be stored in sets and may be exported via wayland directly.
I propose to introduce layer via a new "node" in our object type inheritance tree, e.g. `ws_hashable`.

**Comment by matthiasbeyer** [comment]
We had a mistake in our thoughts:

We must be able to generate a `r_hash` from an object, whereas an UUID is not really helpful for this, is it? The UUID doesn't help us when putting an object into a set, does it?

**Comment by neithernut** [comment]
We can use the UUID as a base for the hash _for wayland related objects_.
So we should still introduce a type `ws_wayland_obj` or something...

**Comment by matthiasbeyer** [comment]
Blocked by missing deps.

**Comment by neithernut** [comment]
The basic (virtual) hash generation functionality for objects does _not_ depend on `wl_display_serial_next()`.

**Comment by matthiasbeyer** [comment]
I'm a bit insecure about how to implement this properly and what are the requirements. I'd suggest to assign this issue to someone else or explaining it to me in detail (no offensive here, though)!

**Comment by neithernut** [comment]
Set the hash function pointer to `NULL` for `ws_object`.
The typed derived from the object type will bring their own implementations. E.g. the string type will use some has algorithm.

As the intrastructure is already merged, we may as well close this issue and create new ones for types which lack hashing functionality.
