### ISSUE TITLE
Create an organisation/project logo

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#7]
It would be pretty neat if we could add an organizations/project logo.

**Comment by neithernut** [comment]
My first take on this is uploaded at http://webuser.hs-furtwangen.de/~ganzjuli/waysome.svg. I didn't got the hair quite right, but it's a start.
Comments?

**Comment by matthiasbeyer** [comment]
Nice. I would make the arms a bit longer, and I would put something on the shirt (like a crossed-out X or something :-P )

**Comment by neithernut** [comment]
As already stated somewhere else, we may create some flavored versions (HFU logo and stuff).
This is the basic logo without anything on the shirt.

**Comment by matthiasbeyer** [comment]
Ok. I really like it, ... but maybe we should add something like trouser pockets (just hinted), so it doesn't look like a pyjama!

**Comment by matthiasbeyer** [comment]
And, well, the hair looks a bit iffy...

**Comment by neithernut** [comment]
I already pointed out the latter one. I'll try to fix that issues until 2014-09-29T16:00CEST.

**Comment by matthiasbeyer** [comment]
Also, if this logo was created by something like metapost or so, we could add a repository containing the logo sources.

I would welcome metapost (or racket?) sources to generate the logo! Would be kind of fun!

**Comment by neithernut** [comment]
The logo was done in inkscape. Also: svgs are XML. As such, they _are_ editable. (I once "wrote" an svg for a scale.)

**Comment by matthiasbeyer** [comment]
XML. Yuck. But hey, Inkscape is a great tool, so I don't blame you for using it!

**Comment by neithernut** [comment]
XML is OK for document and other file formats...
It's just misused in a lot of places.

**Comment by xVin** [comment]
If you want, you can leave graphics stuff to me. I'd work in gimp, though.

**Comment by neithernut** [comment]
The base really should be an svg. It's a lot easier to edit this way. I'm not sure whether gimp can handle vector graphics properly. If you want to, you can download the SVG and mock around with it. As stated above, I'm using [inkscape](http://www.inkscape.org).
However, _after_ the basic figure is done, we may, of course, use raster graphics (e.g. gimp) to fancy things up.

---

I already redid the hair of the figure: http://webuser.hs-furtwangen.de/~ganzjuli/waysome-2.svg
I can add pockets. If everyone is satisfied, I'd add the svg to the repo.

**Comment by xVin** [comment]
I agree that the logo should be a vector image. I'm also not sure if gimp is suited for that task (I usually use Adobe CS progs, just switching to OS tools for the project). I'll give Inkscape a try and see if I am able give the logo a little makeover :)

Just add it to the repo as it is now, I think it's a good starting point.(I wouldnt add pockets.)

**Comment by matthiasbeyer** [comment]
I wouldn't add it to the repo. Binary data in a git repository is always a bad idea.

**Comment by neithernut** [comment]
SVGs are not binary data.

**Comment by matthiasbeyer** [comment]
See #21

**Comment by neithernut** [comment]
I'll reopen that PR as soon as this is set:
We agreed that having a standard-background image is acceptable if it can be generated from a small text file.
The project logo _really should_ go into the repository. It's 94 lines of XML! That's more than acceptable considering that the code base will be two orders of magniture more than that 94 lines.
A meta-post script might be longer _and_ introduce an additional dependency, namely metapost.
