### ISSUE TITLE
Add value type "object_id"

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#71]
We need `ws_value_object_id`.

**Comment by neithernut** [comment]
Blocks #64.

**Comment by matthiasbeyer** [comment]
Q: has this to hold a `ws_object` or a `ws_wayland_obj` ?

**Comment by neithernut** [comment]
It has an object's reference, but it deserializes to an id.

**Comment by matthiasbeyer** [comment]
You mean a hash of a object to identify it in a set?

**Comment by neithernut** [comment]
Nope, not a hash but some sort of id to find it in the world set/object model (which implies that it's only relevant for object types which are in the object model). Should probably be the wayland id.
