### ISSUE TITLE
Create display singleton

### ISSUE THREAD

**Issue by neithernut** [waysome/waysome#74]
We need some initialisation and containment for the `wl_display` instance.
Creation and destruction is straight forward, but as of wayland 1.3 there seems to be no way to retrieve the display. That means that we have to store a pointer to that structure. It's feasible to just have a `extern wl_display* ws_display` in some header.
The interface for that singleton should provide the following:
- Initialisation (and deinitialisation through the cleaner in `src/util`)
- Serial numbers

The question is: where should we put it?
- Not in the compositor, because we use this to retrieve serial numbers, too.
- Utils?

**Comment by neithernut** [comment]
Blocks #66.

**Comment by neithernut** [comment]
Relates to #75.

**Comment by matthiasbeyer** [comment]
Should we add another `util` module for "external singletons"?

**Comment by neithernut** [comment]
A `util` module for wayland related stuff would be much cleaner imho. E.g.

```
util/
util/cleaner.{c,h}
util/wayland.{c,h}
```

**Comment by matthiasbeyer** [comment]
:+1:
